# Generated by Django 3.1.7 on 2021-08-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=12)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('informacion_pedido', models.CharField(max_length=500)),
                ('fecha_entrega', models.DateTimeField()),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('telefono_cliente', models.IntegerField(max_length=10)),
                ('email_cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
